# docker-compose build
# configured for CSE3DMS - Database Management System
# La Trobe University
# Created by Kiki Adhinugraha
# Neo4J
# how to use:
# make sure you have Docker or Docker Desktop installed
# Open the folder that contains docker-compose.yml
# run C:\> docker-compose up

version: '1.0'

services:
  neo4j:
    container_name: neo4j_topic
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"      
    volumes:
#replace the folowing local folder with your local folder where the data will be kept permanently when you turn off your lab computer.
#You may put the working folder in La Trobe OneDrive folder.
      - "C:/dataset/neo4j/data:/data"
      - "C:/dataset/neo4j/logs:/logs"
      - "C:/dataset/neo4j/import:/var/lib/neo4j/import"
      - "C:/dataset/neo4j/plugins:/plugins"      
